### ISSUE TITLE
Log Results

### ISSUE THREAD

**Issue by cpyfferoen** [jeffpriz/vsts-nuspec-reference-update#1]
No indication of what happened, what versions were read, if the files were even found or updated. It's a black box at the moment.

**Comment by jeffpriz** [comment]
thanks for pointing this one out.. I'd put fixing that aside.  I've published a new version (now version 1.0) that takes care of console logging relevant details in the task run instead of relying on running the build with debug set to true.

**Comment by cpyfferoen** [comment]
Thanks! It did however function perfectly!!
Tho, (and this might be a separate issue?) I'm not certain what it's doing for the various [Version ranges and Wildcards](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards)?? 

Maybe just documentation (i.e. "complete ignored"??) for this is sufficient

**Comment by jeffpriz** [comment]
that is a solid issue, that is not really getting supported by this task at this moment.. I need to investigate the way the Nuspec file's handle dependencies for ranges/wildcards.  The task currently doesn't do anything special to take the version info provided in the project file when transferring it to the nuspec.  I just don't know if the nuspec dependency syntax is different than the references syntax.. I'll put that on my backlog

**Comment by cpyfferoen** [comment]
A short scroll down on that link shows the same syntax used in 
- project files (PackageReference)
- packages.config
- .nuspec files

I think updating the Readme to just say that any existing dependency version attributes are ignored, and replaced w/ the "standard" notation (see below) is sufficient at the moment. Anyone more picky about the behavior probably wouldn't consider using this task (or can make a PR to extend the feature set for their needs)

Notation|Applied Rule | Description
-- | -- | --
1.0 | x ≥ 1.0 | Minimum version, inclusive

**Comment by jeffpriz** [comment]
Cool thanks.  If it's the same syntax, the I *think* it should just work as-is. I haven't set up any such references in my test nuget package, but I probably should go do that and see what happens.  Have you attempted to do this? if so, what have you seen as a result?

**Comment by jeffpriz** [comment]
okay, so just to follow up.. I've updated my test Nuget package on my AzureDevOps instance, and I changed my Newtonsoft.json reference to follow a notation other than the "1.0"


Notation | Applied Rule | Description
-- | -- | --
1.0 | x ≥ 1.0 | Minimum version, inclusive


I made it read as [11.0.1,12.0.2] where I had it as 12.0.2 before.. the result worked.. the dependency information showing up after publishing the package to Azure DevOps Artifacts shows as Newtonsoft.Json (≥ 11.0.1 && ≤ 12.0.2) which is correct.. so I feel pretty good that this works regardless of the notation applied.. again, since the notation syntax is the same in the Nuspec as it is in the project reference, this should "just work"
